options:
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  use-corekeeper:
    type: boolean
    default: True
    description: |
      Use corekeeper rather than apport for debugging
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  overlay-network-type:
    default: gre
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
        gre
        vxlan
      .
      Multiple types can be provided - field is space delimited.
